Repository JSK-Labs/PetVerse, pull requests merged in 2025-06, with the labels that each got.

#5 Create README.md
  README.md
Labels: documentation, ODHack14

#8 ✅ Test Scaffold Stark Environment
  packages/nextjs/contracts/deployedContracts.ts
  packages/snfoundry/contracts/.tool-versions
  packages/snfoundry/contracts/Scarb.lock
  packages/snfoundry/contracts/Scarb.toml
Labels: Core Dev, Maintainer - Joseph, Test

#9 added standardized issue template for technical tasks
  .github/issue_template-SCAFFOLD-STARK.md
  README.md
Labels: documentation, Maintainer - Joseph
